//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int Facility_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Facility_Image { get; set; }
    }
}
